on:
  push:
  workflow_dispatch:

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          npx -y @modelcontextprotocol/inspector --cli --method tools/list -- uv run tides.py
        env:
          UKHO_API_KEY: ${{ secrets.UKHO_API_KEY }}