on:
  push:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/setup-uv@v6
      - run: |
          claude mcp add uktides -s project -e UKHO_API_KEY=$UKHO_API_KEY -- uvx uk-tides-mcp
        env:
          UKHO_API_KEY: ${{ secrets.UKHO_API_KEY }}
      - name: Run Claude Code
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "What are the tides in two days time in Fowey?"
          claude_env: |
            DEBUG: true
          allowed_tools: "*"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}